"""add email messages, received hops, auth results, findings

Revision ID: afbb3912daca
Revises: 4ccec320e44b
Create Date: 2026-09-09 13:45:32.417940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbb3912daca'
down_revision = '4ccec320e44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('from_address', sa.String(length=512), nullable=True),
    sa.Column('from_display_name', sa.String(length=512), nullable=True),
    sa.Column('to_addresses', sa.Text(), nullable=True),
    sa.Column('cc_addresses', sa.Text(), nullable=True),
    sa.Column('reply_to', sa.String(length=512), nullable=True),
    sa.Column('return_path', sa.String(length=512), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html_sanitized', sa.Text(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_message_id'), 'email_messages', ['message_id'], unique=False)
    op.create_table('authentication_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('mechanism', sa.String(length=16), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('alignment', sa.String(length=32), nullable=True),
    sa.Column('policy', sa.String(length=32), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('raw_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_refs', sa.Text(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_table('received_hops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('hop_index', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('source_host', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('destination_host', sa.String(length=255), nullable=True),
    sa.Column('protocol', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_private_ip', sa.Boolean(), nullable=False),
    sa.Column('is_malformed', sa.Boolean(), nullable=False),
    sa.Column('missing_data', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('received_hops')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_table('authentication_results')
    op.drop_index(op.f('ix_email_messages_message_id'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
