"""add baseline ML assessments

Revision ID: b49a9a55e7ab
Revises: 51ea66c895b2
Create Date: 2026-09-09 15:06:23.769648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49a9a55e7ab'
down_revision = '51ea66c895b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('email_id', sa.Uuid(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('phishing_probability', sa.Float(), nullable=False),
    sa.Column('bec_probability', sa.Float(), nullable=False),
    sa.Column('impersonation_probability', sa.Float(), nullable=False),
    sa.Column('important_features_json', sa.Text(), nullable=False),
    sa.Column('limitations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_assessments')
    # ### end Alembic commands ###
